language: go

go:
  - 1.x
  - master

os:
  - linux

addons:
  apt:
    packages:
    - qemu

services:
  - docker

env:
  - GO111MODULE=on

install: true

before_script:
  - tools/out-of-tree/bootstrap.sh

script:
  - go test -parallel 1 -v ./...
