language: go

go:
  - master

os:
  - linux

addons:
  apt:
    packages:
    - qemu

services:
  - docker

before_script:
  - cd $GOPATH/src/github.com/jollheef/out-of-tree/tools/qemu-debian-img
  - ./bootstrap.sh