language: go

go:
  - 1.x
  - master

os:
  - linux

addons:
  apt:
    packages:
    - qemu

services:
  - docker

env:
  - GO111MODULE=on

install: true

before_script:
  - cd $GOPATH/src/github.com/jollheef/out-of-tree/tools/qemu-debian-img
  - ./bootstrap.sh
  - cd $GOPATH/src/github.com/jollheef/out-of-tree

script:
  - go test -parallel 1 -v ./...
