language: go

go:
  - 1.x
  - master

os:
  - linux

dist:
  - bionic

addons:
  apt:
    packages:
    - qemu

services:
  - docker

env:
  - GO111MODULE=on

install: true

before_script:
  - ./tools/qemu-debian-img/bootstrap.sh

script:
  - go test -parallel 1 -v ./...
