# out-of-tree configuration file
# docs at https://out-of-tree.io
name = "out-of-tree module example"
type = "module"

[[supported_kernels]]
# Can be Ubuntu/CentOS/Debian/etc.
distro_type = "Ubuntu"
# regex for `uname -r`
# See also: regex-golang.appspot.com
release_mask = "4.4.0-70-.*"

# [[supported_kernels]] may be defined unlimited number of times
[[supported_kernels]]
distro_type = "Ubuntu"
# Also you can use only one kernel
release_mask = "4.15.0-29-generic"
