name: out-of-tree
version: '0.2'
summary: out-of-tree kernel {module, exploit} development tool
description: |
  out-of-tree kernel {module, exploit} development tool

grade: devel
confinement: devmode

parts:
  out-of-tree:
    source: .
    plugin: go
    go-importpath: github.com/jollheef/out-of-tree
    after: [go]
  go:
    source-tag: go1.11.2
    source-depth: 1

apps:
  out-of-tree:
    command: out-of-tree
